hide_window_decorations yes
background_opacity 0.85
background_blur 30

window_padding_width -1

# tab_bar_style fade
tab_bar_edge bottom
tab_bar_style powerline
tab_powerline_style slanted 
tab_bar_align left

font_size 16

cursor_trail 1

shell bash -c "~/.local/bin/terminal-opening-text; exec zsh"
# startup_session ~/.local/bin/terminal-opening-text
